Repository otris/ews-cpp, pull requests merged in 2020-01, with the labels that each got.

#170 Apply clang-format
  include/ews/ews.hpp
Labels: enhancement

#169 Add support of Contact information in Resolve Names resolutions
  include/ews/ews.hpp
  tests/assets/resolve_names_response.xml
  tests/test_resolve_names.cpp
Labels: feature

#166 Fix event_type to and from string
  include/ews/ews.hpp
Labels: bug
